islands.o: islands.c
	gcc -c islands.c

island_hopper: islands.o
	gcc islands.o -o islands

tour.o: tour.c
	gcc -c tour.c

tour_app: tour.o
	gcc tour.o -o tour

SPIES.o: SPIES.c
	gcc -c SPIES.c

spies_app: SPIES.o
	gcc SPIES.o -o spies