fish.o: fish.c
	gcc -c fish.c

fish_printer: fish.o
	gcc fish.o -o fish_printer

turtle_birthday.o: turtle_birthday.c
	gcc -c turtle_birthday.c

turtle_birthday: turtle_birthday.o
	gcc turtle_birthday.o -o turtle_birthday

measurements.o: measurements.c
	gcc -c measurements.c

measurement_display: measurements.o
	gcc measurements.o -o measurement_display